export interface CoinDescription {
  geckoId: string;
  tagline: string;
  description: string;
  launchYear: number;
  category: string;
  consensus: string;
  website: string;
  whitepaper: string;
  explorer: string;
  twitter: string;
}

export const COIN_DESCRIPTIONS: Record<string, CoinDescription> = {
  bitcoin: {
    geckoId: 'bitcoin',
    tagline: 'The original cryptocurrency and global store of value.',
    description: 'Bitcoin was created in 2009 by the pseudonymous Satoshi Nakamoto as a peer-to-peer electronic cash system. It operates on a proof-of-work blockchain secured by a global network of miners. With a hard-capped supply of 21 million coins, Bitcoin is often compared to digital gold and is the largest cryptocurrency by market capitalization. Its security and decentralization have made it the benchmark asset of the entire crypto industry.',
    launchYear: 2009,
    category: 'Store of Value',
    consensus: 'Proof of Work',
    website: 'https://bitcoin.org',
    whitepaper: 'https://bitcoin.org/bitcoin.pdf',
    explorer: 'https://mempool.space',
    twitter: 'https://twitter.com/Bitcoin',
  },
  ethereum: {
    geckoId: 'ethereum',
    tagline: 'The programmable blockchain powering DeFi, NFTs, and Web3.',
    description: 'Ethereum, launched in 2015 by Vitalik Buterin and others, introduced smart contracts — self-executing programs on the blockchain. This enabled decentralized applications (dApps), DeFi protocols, NFT marketplaces, and more. In 2022, Ethereum switched from Proof of Work to Proof of Stake (The Merge), reducing its energy consumption by ~99.9%. Ether (ETH) is used to pay for computation on the network and has the second-largest market cap in crypto.',
    launchYear: 2015,
    category: 'Smart Contract Platform',
    consensus: 'Proof of Stake',
    website: 'https://ethereum.org',
    whitepaper: 'https://ethereum.org/en/whitepaper/',
    explorer: 'https://etherscan.io',
    twitter: 'https://twitter.com/ethereum',
  },
  solana: {
    geckoId: 'solana',
    tagline: 'High-speed blockchain built for decentralized apps at scale.',
    description: 'Solana launched in 2020 with a focus on speed and low transaction costs. Using a novel Proof of History mechanism combined with Proof of Stake, Solana can theoretically process 65,000 transactions per second. It has become a major hub for NFTs, DeFi, and consumer applications. While it has experienced network outages, Solana\'s developer ecosystem and user base have grown significantly, positioning it as a leading Ethereum alternative.',
    launchYear: 2020,
    category: 'Smart Contract Platform',
    consensus: 'Proof of History + Proof of Stake',
    website: 'https://solana.com',
    whitepaper: 'https://solana.com/solana-whitepaper.pdf',
    explorer: 'https://solscan.io',
    twitter: 'https://twitter.com/solana',
  },
  dogecoin: {
    geckoId: 'dogecoin',
    tagline: 'The original meme coin with a passionate community and real-world tipping use.',
    description: 'Dogecoin was created in December 2013 as a joke based on the popular "Doge" internet meme. Despite its origins, it developed one of crypto\'s most enthusiastic communities and is used for social media tipping and microtransactions. It gained mainstream attention in 2021 following celebrity endorsements. Dogecoin uses a Scrypt-based Proof of Work algorithm and has an unlimited supply — around 5 billion new DOGE are mined per year, making it inflationary by design.',
    launchYear: 2013,
    category: 'Meme / Payment',
    consensus: 'Proof of Work (Scrypt)',
    website: 'https://dogecoin.com',
    whitepaper: 'https://github.com/dogecoin/dogecoin',
    explorer: 'https://dogechain.info',
    twitter: 'https://twitter.com/dogecoin',
  },
  cardano: {
    geckoId: 'cardano',
    tagline: 'A research-first blockchain platform built for sustainability and scalability.',
    description: 'Cardano was founded by Charles Hoskinson, a co-founder of Ethereum, and launched in 2017. It is developed by IOHK using peer-reviewed academic research and formal verification methods. Cardano uses the Ouroboros Proof of Stake protocol, which was the first provably secure PoS algorithm. ADA is used for staking, governance, and transaction fees. Cardano has a strong focus on financial inclusion in developing countries and decentralized governance through Project Catalyst.',
    launchYear: 2017,
    category: 'Smart Contract Platform',
    consensus: 'Proof of Stake (Ouroboros)',
    website: 'https://cardano.org',
    whitepaper: 'https://docs.cardano.org/en/latest/',
    explorer: 'https://cardanoscan.io',
    twitter: 'https://twitter.com/Cardano',
  },
  ripple: {
    geckoId: 'ripple',
    tagline: 'A fast settlement network built for cross-border bank payments.',
    description: 'XRP was created by Ripple Labs to enable fast, low-cost international payments. Unlike most cryptocurrencies, XRP does not use proof-of-work or proof-of-stake — instead it relies on a consensus protocol among a network of trusted validators. XRP transactions settle in 3–5 seconds and cost fractions of a cent. Ripple has partnerships with hundreds of financial institutions worldwide. The company faced a major SEC lawsuit in 2020, with a partial resolution reached in 2023 that distinguished XRP sales to retail buyers from institutional sales.',
    launchYear: 2012,
    category: 'Payment / Banking',
    consensus: 'Ripple Protocol Consensus Algorithm',
    website: 'https://ripple.com',
    whitepaper: 'https://ripple.com/files/ripple_consensus_whitepaper.pdf',
    explorer: 'https://xrpscan.com',
    twitter: 'https://twitter.com/Ripple',
  },
  binancecoin: {
    geckoId: 'binancecoin',
    tagline: 'The utility token of the world\'s largest crypto exchange ecosystem.',
    description: 'BNB was launched by Binance in 2017 as an ERC-20 token to pay trading fees at a discount. It later migrated to Binance\'s own BNB Chain (formerly BSC). BNB powers the BNB Smart Chain — a high-throughput blockchain popular for DeFi — and is used for exchange fees, gas, governance, and Binance Launchpad participation. Binance burns BNB quarterly using exchange profits to reduce supply over time, targeting an eventual total supply of 100 million.',
    launchYear: 2017,
    category: 'Exchange Token / Utility',
    consensus: 'Proof of Staked Authority',
    website: 'https://www.bnbchain.org',
    whitepaper: 'https://github.com/bnb-chain/whitepaper',
    explorer: 'https://bscscan.com',
    twitter: 'https://twitter.com/BNBCHAIN',
  },
  'avalanche-2': {
    geckoId: 'avalanche-2',
    tagline: 'An ultra-fast smart contract platform with a unique subnet architecture.',
    description: 'Avalanche launched in 2020, developed by Ava Labs. It uses a novel consensus mechanism called Avalanche Consensus that achieves near-instant finality (under 2 seconds) without sacrificing decentralization. Avalanche consists of three interoperable chains: the X-Chain (for asset exchange), C-Chain (EVM-compatible smart contracts), and P-Chain (validator coordination). Its subnet architecture allows businesses to launch custom blockchains with their own rules while benefiting from Avalanche\'s security.',
    launchYear: 2020,
    category: 'Smart Contract Platform',
    consensus: 'Avalanche Consensus (PoS)',
    website: 'https://www.avax.network',
    whitepaper: 'https://www.avalabs.org/whitepapers',
    explorer: 'https://snowtrace.io',
    twitter: 'https://twitter.com/avalancheavax',
  },
  'matic-network': {
    geckoId: 'matic-network',
    tagline: 'A Layer 2 scaling solution making Ethereum faster and cheaper.',
    description: 'Polygon (originally Matic Network) launched in 2017 to address Ethereum\'s scalability issues. As a Layer 2 network, Polygon processes transactions off the main Ethereum chain and then batches them back — dramatically reducing fees and increasing speed while inheriting Ethereum\'s security. Polygon is EVM-compatible, making it easy for Ethereum developers to deploy apps. It has evolved into a multi-chain ecosystem including zkEVM, the first production zero-knowledge EVM rollup.',
    launchYear: 2017,
    category: 'Layer 2 / Scaling',
    consensus: 'Proof of Stake',
    website: 'https://polygon.technology',
    whitepaper: 'https://polygon.technology/papers',
    explorer: 'https://polygonscan.com',
    twitter: 'https://twitter.com/0xPolygon',
  },
  chainlink: {
    geckoId: 'chainlink',
    tagline: 'The leading decentralized oracle network connecting blockchains to real-world data.',
    description: 'Chainlink, launched in 2019, solves the "oracle problem" — blockchains cannot natively access external data like prices, weather, or sports results. Chainlink\'s decentralized oracle network uses independent node operators who stake LINK as collateral to fetch and verify real-world data on-chain. Smart contracts that depend on accurate external data — DeFi price feeds, insurance, prediction markets — rely on Chainlink. It is the most widely used oracle solution across virtually every major blockchain.',
    launchYear: 2019,
    category: 'Oracle Network',
    consensus: 'Proof of Stake (on Ethereum)',
    website: 'https://chain.link',
    whitepaper: 'https://research.chain.link/whitepaper-v2.pdf',
    explorer: 'https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca',
    twitter: 'https://twitter.com/chainlink',
  },
  litecoin: {
    geckoId: 'litecoin',
    tagline: 'The silver to Bitcoin\'s gold — a faster, lighter payment network.',
    description: 'Litecoin was created in 2011 by Charlie Lee, a former Google engineer, as a lighter alternative to Bitcoin. It uses the Scrypt hashing algorithm instead of SHA-256, making it more accessible to GPU miners. Litecoin has a 4x faster block time than Bitcoin (2.5 min vs 10 min) and a 4x larger maximum supply (84 million LTC). It was one of the first altcoins and has been used to test features like the Lightning Network and SegWit before Bitcoin.',
    launchYear: 2011,
    category: 'Payment / Currency',
    consensus: 'Proof of Work (Scrypt)',
    website: 'https://litecoin.org',
    whitepaper: 'https://github.com/litecoin-project/litecoin',
    explorer: 'https://litecoinspace.org',
    twitter: 'https://twitter.com/LitecoinProject',
  },
  polkadot: {
    geckoId: 'polkadot',
    tagline: 'A multi-chain network enabling different blockchains to interoperate and share security.',
    description: 'Polkadot was founded by Gavin Wood, a co-founder of Ethereum and author of the Ethereum Yellow Paper. It launched in 2020 with a unique "relay chain + parachain" architecture. The relay chain provides shared security for all connected parachains — specialized blockchains that run in parallel and can interoperate with each other. DOT is used for governance, staking, and bonding parachains. Polkadot aims to be the foundational layer connecting an ecosystem of purpose-built blockchains.',
    launchYear: 2020,
    category: 'Multi-Chain / Interoperability',
    consensus: 'Nominated Proof of Stake',
    website: 'https://polkadot.network',
    whitepaper: 'https://polkadot.network/PolkaDotPaper.pdf',
    explorer: 'https://polkadot.subscan.io',
    twitter: 'https://twitter.com/Polkadot',
  },
  'shiba-inu': {
    geckoId: 'shiba-inu',
    tagline: 'The self-styled "Dogecoin killer" with a growing DeFi ecosystem.',
    description: 'Shiba Inu launched in 2020 as an anonymous project and quickly gained attention as a Dogecoin-inspired meme coin. Unlike DOGE, SHIB is an ERC-20 token on Ethereum with a quadrillion initial supply. The Shiba ecosystem includes ShibaSwap (a DEX), two additional tokens (LEASH and BONE), and an NFT collection (Shiboshi). The project has burned significant supply over time. It has a large and active community but remains highly speculative with no fundamental utility beyond its ecosystem.',
    launchYear: 2020,
    category: 'Meme / Ecosystem',
    consensus: 'Proof of Stake (Ethereum)',
    website: 'https://shibatoken.com',
    whitepaper: 'https://github.com/shytoshikusama/woofpaper/raw/main/SHIBA_INU_WOOF_PAPER_V2.pdf',
    explorer: 'https://etherscan.io/token/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE',
    twitter: 'https://twitter.com/Shibtoken',
  },
  uniswap: {
    geckoId: 'uniswap',
    tagline: 'The largest decentralized exchange protocol by volume.',
    description: 'Uniswap, launched in 2018, pioneered the Automated Market Maker (AMM) model — enabling token swaps without an order book through liquidity pools. Users provide tokens in pairs and earn fees from every trade. Uniswap v3 (2021) introduced concentrated liquidity, allowing LPs to allocate capital within specific price ranges for higher capital efficiency. The UNI token was airdropped in 2020 to all historical users and governs the protocol. Uniswap processes billions in volume daily across Ethereum and multiple L2 networks.',
    launchYear: 2018,
    category: 'Decentralized Exchange (DEX)',
    consensus: 'Proof of Stake (Ethereum)',
    website: 'https://uniswap.org',
    whitepaper: 'https://uniswap.org/whitepaper-v3.pdf',
    explorer: 'https://info.uniswap.org',
    twitter: 'https://twitter.com/Uniswap',
  },
  tron: {
    geckoId: 'tron',
    tagline: 'A high-throughput blockchain for decentralized content and stablecoin transfers.',
    description: 'TRON, founded by Justin Sun in 2017, is a high-throughput blockchain designed for content sharing and digital entertainment applications. It uses a Delegated Proof of Stake consensus where 27 "Super Representatives" produce blocks. TRON has become one of the largest networks for USDT (Tether) transfers due to its extremely low fees — making it popular in regions with limited access to traditional banking. TRX is used for fees, resource allocation (Energy and Bandwidth), and governance.',
    launchYear: 2017,
    category: 'Content / Payment',
    consensus: 'Delegated Proof of Stake',
    website: 'https://tron.network',
    whitepaper: 'https://tron.network/static/doc/white_paper_v_2_0.pdf',
    explorer: 'https://tronscan.org',
    twitter: 'https://twitter.com/trondao',
  },
  stellar: {
    geckoId: 'stellar',
    tagline: 'A payment network focused on fast, low-cost cross-border transfers and financial inclusion.',
    description: 'Stellar launched in 2014, founded by Jed McCaleb (an XRP co-creator) and Joyce Kim. It is designed to facilitate currency exchanges and international remittances, particularly for underserved populations. Stellar uses the Stellar Consensus Protocol, a variant of Federated Byzantine Agreement, enabling transactions to settle in 3–5 seconds for minimal fees. The Stellar Development Foundation (SDF) is a nonprofit supporting the ecosystem. USDC (Circle) chose Stellar as one of its main networks alongside Ethereum.',
    launchYear: 2014,
    category: 'Payment / Remittance',
    consensus: 'Stellar Consensus Protocol',
    website: 'https://stellar.org',
    whitepaper: 'https://stellar.org/papers/stellar-consensus-protocol',
    explorer: 'https://stellar.expert',
    twitter: 'https://twitter.com/StellarOrg',
  },
  monero: {
    geckoId: 'monero',
    tagline: 'The leading privacy-focused cryptocurrency with untraceable transactions.',
    description: 'Monero launched in 2014 with a focus on privacy, fungibility, and decentralization. Unlike Bitcoin where all transactions are visible on a public ledger, Monero uses three privacy technologies: Ring Signatures (mix sender with decoys), Stealth Addresses (one-time receive addresses), and RingCT (hides transaction amounts). As a result, Monero transactions are effectively untraceable. This has made it the preferred cryptocurrency for those prioritizing financial privacy — but also attracted regulatory scrutiny. XMR uses Proof of Work with the RandomX algorithm, optimized for CPU mining.',
    launchYear: 2014,
    category: 'Privacy Currency',
    consensus: 'Proof of Work (RandomX)',
    website: 'https://getmonero.org',
    whitepaper: 'https://getmonero.org/resources/research-lab/',
    explorer: 'https://xmrchain.net',
    twitter: 'https://twitter.com/monero',
  },
  cosmos: {
    geckoId: 'cosmos',
    tagline: 'The "Internet of Blockchains" — an ecosystem of interoperable chains.',
    description: 'Cosmos, launched in 2019 by Tendermint (now Ignite), aims to solve blockchain interoperability through the Inter-Blockchain Communication (IBC) protocol. The Cosmos SDK allows developers to build application-specific blockchains (zones) that can communicate with each other and exchange assets via IBC. The Cosmos Hub is the main chain where ATOM is staked. Notable projects built on Cosmos include Osmosis (largest IBC DEX), dYdX, and Celestia. The network uses Tendermint BFT consensus achieving instant finality.',
    launchYear: 2019,
    category: 'Interoperability / Layer 0',
    consensus: 'Tendermint BFT (Proof of Stake)',
    website: 'https://cosmos.network',
    whitepaper: 'https://cosmos.network/cosmos-whitepaper.pdf',
    explorer: 'https://www.mintscan.io/cosmos',
    twitter: 'https://twitter.com/cosmos',
  },
};

export function getCoinDescription(geckoId: string): CoinDescription | null {
  return COIN_DESCRIPTIONS[geckoId] ?? null;
}
